version = 1
SPDX-PackageName = "btp-business-application-studio"
SPDX-PackageSupplier = "NAME SURNAME (EMAIL)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/YOUR-REPOSITORY"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2023 SAP SE or an SAP affiliate company and YOUR-REPOSITORY contributors"
SPDX-License-Identifier = "CC-BY-4.0"
